import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
        sans:     ["Inter", "system-ui", "sans-serif"],
      },
      colors: {
        // Material Design 3 - "The Tactile Artisan" theme
        "surface-dim":                "#d9dadb",
        "secondary-fixed-dim":        "#fdb881",
        "on-tertiary-container":      "#004360",
        "on-secondary-fixed-variant": "#6a3b0f",
        "secondary-container":        "#fdb881",
        "surface-container-high":     "#e7e8e9",
        "primary-fixed":              "#ffdcc3",
        "primary":                    "#904d00",
        "on-secondary":               "#ffffff",
        "on-primary-fixed-variant":   "#6e3900",
        "background":                 "#f8f9fa",
        "tertiary":                   "#00658f",
        "on-tertiary-fixed":          "#001e2e",
        "surface-bright":             "#f8f9fa",
        "on-tertiary-fixed-variant":  "#004c6c",
        "on-primary":                 "#ffffff",
        "inverse-surface":            "#2e3132",
        "on-surface-variant":         "#564334",
        "on-secondary-fixed":         "#2f1500",
        "secondary-fixed":            "#ffdcc3",
        "primary-container":          "#ff8c00",
        "tertiary-container":         "#00b5fc",
        "error-container":            "#ffdad6",
        "secondary":                  "#865224",
        "on-background":              "#191c1d",
        "outline-variant":            "#ddc1ae",
        "tertiary-fixed-dim":         "#85cfff",
        "on-primary-fixed":           "#2f1500",
        "surface-tint":               "#904d00",
        "on-surface":                 "#191c1d",
        "inverse-primary":            "#ffb77d",
        "on-secondary-container":     "#78471a",
        "surface-container-highest":  "#e1e3e4",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "primary-fixed-dim":          "#ffb77d",
        "surface-container-lowest":   "#ffffff",
        "surface-variant":            "#e1e3e4",
        "on-primary-container":       "#623200",
        "outline":                    "#897362",
        "surface-container":          "#edeeef",
        "surface-container-low":      "#f3f4f5",
        "inverse-on-surface":         "#f0f1f2",
        "on-tertiary":                "#ffffff",
        "on-error-container":         "#93000a",
        "surface":                    "#f8f9fa",
        "tertiary-fixed":             "#c7e7ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        md:      "0.25rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "0.75rem",
        "3xl":   "1rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
